// export const seedActivities = [
//   {
//     id: 1,
//     name: 'Soldar',
//     classification: 'VAA',
//     typeMovimation: 'SOLDAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 2,
//     name: 'Montar',
//     classification: 'VAA',
//     typeMovimation: 'MONTAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 3,
//     name: 'Caminhar máquina',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 4,
//     name: 'Caminhar peça',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 5,
//     name: 'Caminhar ferramenta/dispositivo',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 6,
//     name: 'Caminhar EPI',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 7,
//     name: 'Caminhar talha/ponte rolante',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 8,
//     name: 'Caminhar OF',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 9,
//     name: 'Limpar respingo',
//     classification: 'NVAA',
//     typeMovimation: 'LIMPAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 10,
//     name: 'Ajustar peça',
//     classification: 'NVAA',
//     typeMovimation: 'AJUSTAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 11,
//     name: 'Ajustar ferramenta/dispositivo',
//     classification: 'NVAA',
//     typeMovimation: 'AJUSTAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 12,
//     name: 'Aplicar antirespingo/pré-aquecer',
//     classification: 'SVAA',
//     typeMovimation: 'PEGAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 13,
//     name: 'Aplicar LP/revelador',
//     classification: 'SVAA',
//     typeMovimation: 'PEGAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 14,
//     name: 'Utilizar lixadeira',
//     classification: 'NVAA',
//     typeMovimation: 'RETRABALHAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 15,
//     name: 'Utilizar marreta',
//     classification: 'NVAA',
//     typeMovimation: 'RETRABALHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 16,
//     name: 'Caminhar insumos/MP',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 17,
//     name: 'Controle de qualidade',
//     classification: 'NVAA',
//     typeMovimation: 'INSPECIONAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 18,
//     name: 'Tipar',
//     classification: 'VAA',
//     typeMovimation: 'IDENTIFICAR',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 19,
//     name: 'Necessidades pessoais',
//     classification: 'NVAA',
//     typeMovimation: 'OUTROS',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 20,
//     name: 'Tirar medida (Robô)',
//     classification: 'NVAA',
//     typeMovimation: 'OUTROS',
//     activityType: 'SOLDAGEM',
//   },
//   {
//     id: 21,
//     name: 'Posicionar peça',
//     classification: 'SVAA',
//     typeMovimation: 'POSICIONAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 22,
//     name: 'Caminhar talha/ponte rolante',
//     classification: 'NVAA',
//     typeMovimation: 'CAMINHAR',
//     activityType: 'AMBOS',
//   },
//   {
//     id: 23,
//     name: 'Limpar peça',
//     classification: 'NVAA',
//     typeMovimation: 'LIMPAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 24,
//     name: 'Lixar peça',
//     classification: 'NVAA',
//     typeMovimation: 'RETRABALHAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 25,
//     name: 'Aplicar unichem',
//     classification: 'NVAA',
//     typeMovimation: 'AJUSTAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 26,
//     name: 'Aplicar graxa',
//     classification: 'NVAA',
//     typeMovimation: 'AJUSTAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 27,
//     name: 'Utilizar retífica',
//     classification: 'NVAA',
//     typeMovimation: 'RETRABALHAR',
//     activityType: 'MONTAGEM',
//   },
//   {
//     id: 28,
//     name: 'Ar comprimido',
//     classification: 'NVAA',
//     typeMovimation: 'LIMPAR',
//     activityType: 'MONTAGEM',
//   },
// ];
export const seedActivities = [
  {
    id: 1,
    name: 'Soldar',
    classification: 'VAA',
    typeMovimation: 'SOLDAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 2,
    name: 'Montar',
    classification: 'VAA',
    typeMovimation: 'MONTAR',
    activityType: 'GERAL',
  },
  {
    id: 3,
    name: 'Caminhar máquina',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 4,
    name: 'Caminhar peça',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 5,
    name: 'Caminhar ferramenta/dispositivo',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 6,
    name: 'Caminhar EPI',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 7,
    name: 'Caminhar talha/ponte rolante',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 8,
    name: 'Caminhar OF',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 9,
    name: 'Limpar respingo',
    classification: 'NVAA',
    typeMovimation: 'LIMPAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 10,
    name: 'Ajustar peça',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'GERAL',
  },
  {
    id: 11,
    name: 'Ajustar ferramenta/dispositivo',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 12,
    name: 'Aplicar antirespingo/pré-aquecer',
    classification: 'SVAA',
    typeMovimation: 'PEGAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 13,
    name: 'Aplicar LP/revelador',
    classification: 'SVAA',
    typeMovimation: 'PEGAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 14,
    name: 'Utilizar lixadeira',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 15,
    name: 'Utilizar marreta',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
    activityType: 'GERAL',
  },
  {
    id: 16,
    name: 'Caminhar insumos/MP',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
    activityType: 'GERAL',
  },
  {
    id: 17,
    name: 'Controle de qualidade',
    classification: 'NVAA',
    typeMovimation: 'INSPECIONAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 18,
    name: 'Tipar',
    classification: 'VAA',
    typeMovimation: 'IDENTIFICAR',
    activityType: 'SOLDAGEM',
  },
  {
    id: 19,
    name: 'Necessidades pessoais',
    classification: 'NVAA',
    typeMovimation: 'OUTROS',
    activityType: 'GERAL',
  },
  {
    id: 20,
    name: 'Tirar medida (Robô)',
    classification: 'NVAA',
    typeMovimation: 'OUTROS',
    activityType: 'SOLDAGEM',
  },
  {
    id: 21,
    name: 'Posicionar peça',
    classification: 'SVAA',
    typeMovimation: 'POSICIONAR',
    activityType: 'GERAL',
  },
  {
    id: 23,
    name: 'Limpar peça',
    classification: 'NVAA',
    typeMovimation: 'LIMPAR',
    activityType: 'GERAL',
  },
  {
    id: 24,
    name: 'Lixar peça',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
    activityType: 'GERAL',
  },
  {
    id: 25,
    name: 'Aplicar unichem',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'MONTAGEM',
  },
  {
    id: 26,
    name: 'Aplicar graxa',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'MONTAGEM',
  },
  {
    id: 27,
    name: 'Utilizar retífica',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
    activityType: 'MONTAGEM',
  },
  {
    id: 28,
    name: 'Ar comprimido',
    classification: 'NVAA',
    typeMovimation: 'LIMPAR',
    activityType: 'MONTAGEM',
  },
  {
    id: 29,
    name: 'Usinar',
    classification: 'VAA',
    typeMovimation: 'USINAR',
    activityType: 'USINAGEM',
  },
  {
    id: 30,
    name: 'Fixar peça no dispositivo',
    classification: 'SVAA',
    typeMovimation: 'POSICIONAR',
    activityType: 'USINAGEM',
  },
  {
    id: 31,
    name: 'Limpar máquina',
    classification: 'NVAA',
    typeMovimation: 'LIMPAR',
    activityType: 'GERAL',
  },
  {
    id: 32,
    name: 'Ajustar parâmetros no CNC (avanço/rotação)',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'USINAGEM',
  },
  {
    id: 33,
    name: 'Abrir/fechar porta da máquina',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'USINAGEM',
  },
  {
    id: 34,
    name: 'Montar/ajustar ferramentas na máquina',
    classification: 'SVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'GERAL',
  },
  {
    id: 35,
    name: 'Dobrar',
    classification: 'VAA',
    typeMovimation: 'DOBRAR',
    activityType: 'DOBRA',
  },
  {
    id: 36,
    name: 'Posicionar peça para dobrar',
    classification: 'SVAA',
    typeMovimation: 'POSICIONAR',
    activityType: 'DOBRA',
  },
  {
    id: 37,
    name: 'Ajustar máquina',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'DOBRA',
  },
  {
    id: 38,
    name: 'Medir peça',
    classification: 'SVAA',
    typeMovimation: 'MEDIR',
    activityType: 'DOBRA',
  },
  {
    id: 39,
    name: 'Ajustar parâmetros no CNC',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
    activityType: 'DOBRA',
  },
];
