export const seedActivities = [
  {
    id: 1,
    name: 'Soldar',
    classification: 'VAA',
    typeMovimation: 'SOLDAR',
  },
  {
    id: 2,
    name: 'Montar',
    classification: 'VAA',
    typeMovimation: 'MONTAR',
  },
  {
    id: 3,
    name: 'Caminhar máquina',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 4,
    name: 'Caminhar peça',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 5,
    name: 'Caminhar ferramenta/dispositivo',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 6,
    name: 'Caminhar EPI',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 7,
    name: 'Caminhar talha/ponte rolante',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 8,
    name: 'Caminhar OF',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 9,
    name: 'Limpar respingo',
    classification: 'NVAA',
    typeMovimation: 'LIMPAR',
  },
  {
    id: 10,
    name: 'Ajustar peça',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
  },
  {
    id: 11,
    name: 'Ajustar ferramenta/dispositivo',
    classification: 'NVAA',
    typeMovimation: 'AJUSTAR',
  },
  {
    id: 12,
    name: 'Aplicar antirespingo/pré-aquecer',
    classification: 'SVAA',
    typeMovimation: 'PEGAR',
  },
  {
    id: 13,
    name: 'Aplicar LP/revelador',
    classification: 'SVAA',
    typeMovimation: 'PEGAR',
  },
  {
    id: 14,
    name: 'Utilizar lixadeira',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
  },
  {
    id: 15,
    name: 'Utilizar marreta',
    classification: 'NVAA',
    typeMovimation: 'RETRABALHAR',
  },
  {
    id: 16,
    name: 'Caminhar insumos/MP',
    classification: 'NVAA',
    typeMovimation: 'CAMINHAR',
  },
  {
    id: 17,
    name: 'Controle de qualidade',
    classification: 'NVAA',
    typeMovimation: 'INSPECIONAR',
  },
  {
    id: 18,
    name: 'Tipar',
    classification: 'VAA',
    typeMovimation: 'IDENTIFICAR',
  },
  {
    id: 19,
    name: 'Necessidades pessoais',
    classification: 'NVAA',
    typeMovimation: 'OUTROS',
  },
  {
    id: 20,
    name: 'Tirar medida (Robô)',
    classification: 'NVAA',
    typeMovimation: 'OUTROS',
  },
];
